### ISSUE TITLE
Help Run Workflows for Old PCAWG Pipeline

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#290]
@lindaxiang to fill in details
Got a request from Lincoln's group to run Alignment + Sanger pipelines through their data:
- data size is ~30TB for ~30 donors
- each donor has 1 normal + multiple tumours
- need to download data from EGA

The plan is:
- make use of `argo-data-submission-wf` to download and submit data to `rdpc-qa`
- run the ARGO pipeline with GRCh37 on the data
- may need to utilize` rdpc-prod`'s computing resource to run the pipeline if `rdpc-qa` lacks the needed resource.

**Comment by b-f-chan** [comment]
@lindaxiang to add some details about the current execution status, can go on for quite a while since there's a lot of data to help Lincoln process

Will also assign @edsu7 for assistance

**Comment by puneet-oicr** [comment]
No new updates

**Comment by puneet-oicr** [comment]
Waiting for email response for further direction from EGA

**Comment by b-f-chan** [comment]
EGA py download client still being used, was going slow, so we implemented some code changes on OICR side to speed it up; they were also trying to get a DBox for faster transfer

@edsu7 will follow-up to see where EGA is at in terms of status before we do next step

**Comment by edsu7** [comment]
Xindi is now using Aspera portion of the pipeline as a test.

**Comment by b-f-chan** [comment]
Additional tickets have been opened in response to this, see blocked ticket above

**Comment by edsu7** [comment]
Test example successful:
```
https://submission-song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/4440f0ae-ccc2-4b84-80f0-aeccc2cb849c
```
One hiccup was that the fileSize provided by EGA is incorrect (off by a few bytes, but Md5sum is consistent) triggering our checks:
```
"The fileSize calculated from the sequencing files does NOT match the info provided in metadata JSON. Details of the difference: [DTB-097-Progression-cfDNA_1.fq.gz: fileSize: 169568827810 vs 169568827826]; [DTB-097-Progression-cfDNA_2.fq.gz: fileSize: 191746184519 vs 191746184535]
```

If all other samples have the same issue, it means triggering the pipeline to download via aspera, failing, resubmitting via local

**Comment by edsu7** [comment]
Should roughly take around 11 hours for submission. 9h 36m 2s + 5h 35m 22s - 4 hr  ( redundant valSeq operations).

Timebreak down:


```
59/1d591b       ArgoDataSubmissionWf:sanityCheck        3.7s    2 GB
67/75270c       ArgoDataSubmissionWf:checkCramReference 1ms     -
f4/1b660e       ArgoDataSubmissionWf:pGenExp    1.8s    8 GB
b4/01ba2c       ArgoDataSubmissionWf:egaWf:downloadAspera (1)   3h 53m 13s      8 GB
42/2c1240       ArgoDataSubmissionWf:egaWf:downloadAspera (2)   4h 24m 6s       8 GB
46/47f611       ArgoDataSubmissionWf:egaWf:decryptAspera (1)    1h 6m 57s       8 GB
e3/b43997       ArgoDataSubmissionWf:egaWf:decryptAspera (2)    1h 1m 56s       8 GB
46/7ef90b       ArgoDataSubmissionWf:valSeq     4h 9m 51s       16 GB
4c/864012       ArgoDataSubmissionWf:egaWf:cleanup      8.5s    2 GB
```
```
59/1d591b       ArgoDataSubmissionWf:sanityCheck        3.7s    2 GB
33/2f4cbd       ArgoDataSubmissionWf:pGenExp    2.3s    8 GB
ab/67d85c       ArgoDataSubmissionWf:checkCramReference 2ms     -
1a/fed9ea       ArgoDataSubmissionWf:valSeq     4h 3m 10s       16 GB
36/4b6583       ArgoDataSubmissionWf:uploadWf:songSub (UBCPC-CA)        7s      2 GB
67/23ea1c       ArgoDataSubmissionWf:uploadWf:songMan (4440f0ae-ccc2-4b84-80f0-aeccc2cb849c)    3.2s    2 GB
b8/9b12b0       ArgoDataSubmissionWf:uploadWf:scoreUp (4440f0ae-ccc2-4b84-80f0-aeccc2cb849c)    1h 31m 43s      10 GB
5d/58a198       ArgoDataSubmissionWf:uploadWf:songPub (4440f0ae-ccc2-4b84-80f0-aeccc2cb849c)    6.1s    2 GB
63/ac80b9       ArgoDataSubmissionWf:submissionReceipt  3s      1 GB
d9/538c94       ArgoDataSubmissionWf:printOut   27ms    -
```

**Comment by edsu7** [comment]
Steps with room for improvement :`seq-tools`

Break down of time spent per test in `seq-tools` 
|Time|Test|
|---|---|
|3:32:01|c609_fastq_sanity|
|0:31:05|c683_fileMd5sum_match|
|<0:1:0|c110_rg_id_uniqueness|
|<0:1:0|c120_permissible_char_in_rg_id|
|<0:1:0|c130_one_sample|
|<0:1:0|c140_platform_unit_uniqueness|
|<0:1:0|c150_rg_count_match|
|<0:1:0|c160_file_r1_r2_check|
|<0:1:0|c170_fq_uniqueness_in_rgs|
|<0:1:0|c180_file_uniqueness|
|<0:1:0|c190_no_extra_files|
|<0:1:0|c200_rg_id_in_bam_uniqueness|
|<0:1:0|c210_no_path_in_filename|
|<0:1:0|c220_no_rg_id_in_bam_for_fq|
|<0:1:0|c230_files_info_data_category|
|<0:1:0|c240_submitter_rg_id_collide_with_rg_id_in_bam|
|<0:1:0|c250_file_data_type|
|<0:1:0|c260_filename_pattern|
|<0:1:0|c605_all_files_accessible|
|<0:1:0|c608_bam_sanity|
|<0:1:0|c610_rg_id_in_bam|
|<0:1:0|c620_submitter_read_group_id_match|
|<0:1:0|c630_rg_id_in_bam_match|
|<0:1:0|c640_one_sm_in_bam_header|
|<0:1:0|c650_sm_in_bam_matches_metadata|
|<0:1:0|c660_metadata_in_bam_rg_header|
|<0:1:0|c670_rg_is_paired_in_bam|
|<0:1:0|c680_repeated_read_names_per_group_in_bam|
|<0:1:0|c681_fileSize_match|

**Comment by lindaxiang** [comment]
- Spin up more VM to process the data

**Comment by lindaxiang** [comment]
> Test example successful:
> 
> ```
> https://submission-song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/4440f0ae-ccc2-4b84-80f0-aeccc2cb849c
> ```
> 
> One hiccup was that the fileSize provided by EGA is incorrect (off by a few bytes, but Md5sum is consistent) triggering our checks:
> 
> ```
> "The fileSize calculated from the sequencing files does NOT match the info provided in metadata JSON. Details of the difference: [DTB-097-Progression-cfDNA_1.fq.gz: fileSize: 169568827810 vs 169568827826]; [DTB-097-Progression-cfDNA_2.fq.gz: fileSize: 191746184519 vs 191746184535]
> ```
> 
> If all other samples have the same issue, it means triggering the pipeline to download via aspera, failing, resubmitting via local

Considering this issue could exist for all the samples, one walk around could be we add an option in the `payload-generation` to enable the calculation of the fileSize and md5sum on the fly instead of getting it from users' inputs. 
However this option will only be used when the user are not certain of their data's accurate fileSize and md5Sum.

**Comment by edsu7** [comment]
Noticed test names were incorrect comment : https://github.com/icgc-argo/workflow-roadmap/issues/290#issuecomment-1412210342 has been updated

**Comment by edsu7** [comment]
Some tests comparing methods:
old implementation:
```
time (cat TCRBOA7-T-WEX.read1.fastq.gz | zcat | wc -l)
real	2m34.287s
user	2m23.354s
sys	0m11.090s
```
Current implementation:
```
time (unpigz -p 8 -c TCRBOA7-T-WEX.read1.fastq.gz | wc -l)
real	1m23.027s
user	1m35.180s
sys	0m18.525s
```
Seqkit:
```
time seqkit stats -j 8 TCRBOA7-T-WEX.read1.fastq.gz
real	2m12.563s
user	2m36.014s
sys	0m2.980s
```

Could reasonably cut down seq-tools' 3 hours by 40%, but would mean step is about an hour long.

**Comment by puneet-oicr** [comment]
Changes made to improve testing time - 3 hours to 1 time. PR created.

**Comment by lindaxiang** [comment]
Workflow running status sheet: https://docs.google.com/spreadsheets/d/1HY1xMawKbB6pEBQSgTUR82bpagnzHeetgJIfdaPSIGk/edit#gid=0

Currently the alignment runs are blocked by the [score downloading issue form RDPC-QA score](https://github.com/icgc-argo/workflow-roadmap/issues/333)

**Comment by puneet-oicr** [comment]
Waiting on Xindi

**Comment by edsu7** [comment]
- Not using PCAWG, using ARGO pipelines (will run both sanger and mutect)
- She would would also like consensus calls
- Keep genome build on hg19
- preliminary estimates. and time lines are :
 - 1.5 months for data submission
   - 2 months for data processing
   - Xindi would like to have some data to look at by June
   - Full delivery by August?

To touch base in a week, will determine if more help is needed and update timelines

**Comment by puneet-oicr** [comment]
Edmund to check again the estimates with Xindi

**Comment by edsu7** [comment]
One of Xindi's uploads encountered the old error:
![image](https://user-images.githubusercontent.com/22638361/228249813-fd0eee65-0b98-4760-a4e0-07ca644b0bff.png)


List of analyses:
https://submission-song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/dc467237-dd66-4b34-8672-37dd661b34b4
https://submission-song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/9717240f-8e37-4a1d-9724-0f8e378a1d38

A second attempt at reupload was successful. Will continue to document if more cases pop up

**Comment by puneet-oicr** [comment]
Continue observing how stable score is. Song/score JDK issue resolution may help

**Comment by puneet-oicr** [comment]
Touchbase with Xindi, all good so far. Tumor samples uploaded so far
Score issue which was a blocker is resolved.

**Comment by puneet-oicr** [comment]
To check on Xindi's updates

**Comment by edsu7** [comment]
53/110 datasets submitted
3/110 aligned

**Comment by edsu7** [comment]
Jobs failed b/c of `NULL` string value supplied as date was uninterpretable by tool. Went into song and modified all values to be `null`. Example IDs:
https://wes.rdpc.cancercollaboratory.org/runs/wes-79826ebfcf1f4e749d264ca09a61c0e2

Retriggering of jobs still failed. Trouble shooting Ids:
https://wes.rdpc.cancercollaboratory.org/runs/wes-1453c932f16b44b09267716fd3793fdc
https://wes.rdpc.cancercollaboratory.org/runs/wes-903d0e6ea99a46cabab1be5c1cd65a98

**Comment by edsu7** [comment]
Linda will submit some variance calling jobs.

**Comment by lindaxiang** [comment]
The song schemas:
- sequencing_alignment
- qc_metrics
- variant_calling
- variant_calling_supplement 

in [QA](https://song.rdpc-qa.cancercollaboratory.org/) are temporarily changed to accommodate the value:
```
"platform": "Illumina",
```
which are the existing values in UBCPC-CA payloads.
After we finish this batch of jobs running for UBCPC-CA, we will update them to the fixed versions. 
Related issues:
- https://github.com/icgc-argo/workflow-roadmap/issues/355
- https://github.com/icgc-argo/argo-metadata-schemas/issues/69

**Comment by edsu7** [comment]
53/110 datasets submitted
31/110 aligned
2/60 Sanger variant calling

@edsu7 to ping Xindi to submit more data

**Comment by edsu7** [comment]
53/110 datasets submitted
31/110 aligned
2/60 Sanger variant calling

@edsu7 to ping Xindi to submit more data

**Comment by lindaxiang** [comment]
Status on May31,2023
- Submission: 54/110 datasets submitted
- Alignment:  37/54 complete, 12/54 running in progress, 5/54 in backlog
- Sanger variant calling: 8/60 complete, 9/60 in progress, 3/60 failed

**Comment by lindaxiang** [comment]
June26, UBCPC-CA sanger wgs jobs failures summary:
- Type-1: 137 OOM issue of PINDEL

```
1. https://wes.rdpc.cancercollaboratory.org/runs/wes-246ab0ce2dc24da0a2d466683ddbcf6f
2. https://wes.rdpc.cancercollaboratory.org/runs/wes-d7a45394b421425a947dca04770a906d
3. https://wes.rdpc.cancercollaboratory.org/runs/wes-bebcd0572ece4e32a82ec5ccb04612c3
```
Todo: `decrease cpus=16, pindelcpu=2 and re-run`

- Type-2: 137 OOM issue of CAVEMAN

```
1. https://wes.rdpc.cancercollaboratory.org/runs/wes-dfa53280fafa43e1b1aa5f7a42a24e0f
2. https://wes.rdpc.cancercollaboratory.org/runs/wes-fa9b01f0f8374439bc814560c1347a84
```
Todo: `decrease cpus=16, pindelcpu=2 and re-run`

- Type-3: not sure the reason
```
1. https://wes.rdpc.cancercollaboratory.org/runs/wes-e21f9d4ade474302b81b817b97319faf
```
Todo: `not sure the reason, re-run with decreased cpus=16 and pindelcpu=2`

- Type-4: workDir was cleaned?? 
```
1. https://wes.rdpc.cancercollaboratory.org/runs/wes-c11954a6a47c41a1bf524de06718bbaa
2. https://wes.rdpc.cancercollaboratory.org/runs/wes-b1698ba5dbb34ba5a957020697b6e082
3. https://wes.rdpc.cancercollaboratory.org/runs/wes-3f5e46dc422e418ab085f100291f3a7c
```
Todo: `decrease cpus=16, pindelcpu=2 and re-run`

**Comment by edsu7** [comment]
Ten runs failed because API token expiry. Pipeline was restarted from repack step with a new QA token. All ten runs were successful reuploaded.

2 failed runs were restarted with more memory and 10 more runs were queued

**Comment by edsu7** [comment]
Investigating:
```
https://wes.rdpc.cancercollaboratory.org/runs/wes-23760293b6794c2a9f16e6476dc9093d
```

Solution:
- Resubmit as a new analysis with corrected CRAM header and experiment value and restart run

BreakDown:
- Tracking down the error log
```
/nfs/nfs-1/vol-1/work/89/33e9782925071ad1b351148af57aee/WGS_SA626355_vs_SA626362/caveman/tmpCaveman/logs/Sanger_CGP_Caveman_Implement_caveman_estep.1.err
```

- yields the error
```
[ERROR] (src/output.c: output_vcf_header:279 errno: None) Normal and tumour platforms don't match: 'Illumina' ne 'ILLUMINA'
```
- Checking the following analyses shows wrong illumina:
```https://song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/2a7782f8-1e32-4226-b782-f81e32a22621
https://song.rdpc-qa.cancercollaboratory.org/studies/UBCPC-CA/analysis/a15d17b2-ead2-4cd9-9d17-b2ead2acd960
```

**Comment by edsu7** [comment]
Investigating:
```
https://wes.rdpc.cancercollaboratory.org/runs/wes-5ef4576ba38c45738f07afebaaf1e2d6
```

Breakdown:
- Caveman log
```
/nfs/nfs-1/vol-1/work/e0/663460009baad5b4444a1261a9d052/timings/WGS_SA626407_vs_SA626449.time.CaVEMan
```
- that is failing b/c of
```
# ERROR: normal-contamination should be <1 even if from ASCAT.samplestatistics.csv file (1).

Command exited with non-zero status 1
	Command being timed: "caveman.pl -r /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/genome.fa.fai -ig /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/caveman/HiDepth.tsv -b /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/caveman/flagging -ab /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/vagrent -u /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/caveman -s human -sa GRCh38 -t 24 -st WGS -tc /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/tmp/tum.cn.bed -nc /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/tmp/norm.cn.bed -td 5 -nd 2 -tb /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/tmp/SA626407.cram -nb /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/tmp/SA626449.cram -c /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/flag.vcf.config.WGS.ini -f /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/reference_files/caveman/flagging/flag.to.vcf.convert.ini -e 800000 -o /nfs-1-c1/work/e0/663460009baad5b4444a1261a9d052/WGS_SA626407_vs_SA626449/caveman -x chrUn%,HLA%,%_alt,%_random,chrM,chrEBV -k 1 -no-flagging -noclean"
```
- samplestatistics.csv in quesiton
```
/nfs/nfs-1/vol-1/work/e0/663460009baad5b4444a1261a9d052/WGS_SA626407_vs_SA626449/ascat/SA626407.samplestatistics.txt
```
- who's contents suggest ascat did not run properly
```
## WARNING ASCAT failed to generate a solution ##
NormalContamination 0.3
Ploidy ?
rho 0
psi 0
goodnessOfFit 0
GenderChr Y
GenderChrFound Y
```
- expected value
```
NormalContamination 0.254687915729116
Ploidy 3.43732814235995
rho 0.63
psi 3.3
goodnessOfFit 92.643980167822
GenderChr Y
GenderChrFound Y
```

**Comment by lindaxiang** [comment]
@edsu7 there were some runs having the same issue as the second one you mentioned:
https://github.com/icgc-argo/workflow-roadmap/issues/144

**Comment by edsu7** [comment]
Currently all jobs have been completed, waiting for more samples to be submitted:

53/110 datasets submitted
53/110 aligned
29/60 Sanger variant calling (1 iceboxed due to https://github.com/icgc-argo/workflow-roadmap/issues/290#issuecomment-1648374967)

Have notified Xindi about data availability as well as impending affects of collab's shutdown on processing.

**Comment by edsu7** [comment]
Updating Xindi submitted more samples:
90/110 datasets submitted
53/110 aligned
29/60 Sanger variant calling (1 iceboxed due to https://github.com/icgc-argo/workflow-roadmap/issues/290#issuecomment-1648374967)
